#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_listing_Page.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="productdb")]
	public partial class ProduDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ProduDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["productdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProduDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Filter2022")]
		public ISingleResult<Filter2022Result> Filter2022()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Filter2022Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Index_20229")]
		public ISingleResult<Index_20229Result> Index_20229()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Index_20229Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductID_2022")]
		public ISingleResult<ProductID_2022Result> ProductID_2022([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<ProductID_2022Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Imag_20220907")]
		public ISingleResult<Imag_20220907Result> Imag_20220907()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Imag_20220907Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Register20220909")]
		public ISingleResult<Register20220909Result> Register20220909([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(200)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(200)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(20)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Department", DbType="NVarChar(200)")] string department, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hobbies", DbType="NVarChar(200)")] string hobbies)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, emailAddress, password, gender, department, hobbies);
			return ((ISingleResult<Register20220909Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkEmailInDB")]
		public int checkEmailInDB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Emailaddress", DbType="NVarChar(200)")] string emailaddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emailaddress);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Filter2022Result
	{
		
		private int _Id;
		
		private string _Title;
		
		private string _Detail1;
		
		private string _Detail2;
		
		public Filter2022Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail1", DbType="NVarChar(200)")]
		public string Detail1
		{
			get
			{
				return this._Detail1;
			}
			set
			{
				if ((this._Detail1 != value))
				{
					this._Detail1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail2", DbType="NVarChar(200)")]
		public string Detail2
		{
			get
			{
				return this._Detail2;
			}
			set
			{
				if ((this._Detail2 != value))
				{
					this._Detail2 = value;
				}
			}
		}
	}
	
	public partial class Index_20229Result
	{
		
		private int _id;
		
		private string _ImagePath1;
		
		private string _ImagePath2;
		
		private string _ImageName;
		
		private string _Categroies;
		
		private System.Nullable<decimal> _Price;
		
		public Index_20229Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath1", DbType="NVarChar(200)")]
		public string ImagePath1
		{
			get
			{
				return this._ImagePath1;
			}
			set
			{
				if ((this._ImagePath1 != value))
				{
					this._ImagePath1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath2", DbType="NVarChar(200)")]
		public string ImagePath2
		{
			get
			{
				return this._ImagePath2;
			}
			set
			{
				if ((this._ImagePath2 != value))
				{
					this._ImagePath2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(200)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this._ImageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categroies", DbType="NVarChar(200)")]
		public string Categroies
		{
			get
			{
				return this._Categroies;
			}
			set
			{
				if ((this._Categroies != value))
				{
					this._Categroies = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
	
	public partial class ProductID_2022Result
	{
		
		private string _ImgName;
		
		private string _imgpath;
		
		private string _Catogries;
		
		private int _id;
		
		private System.Nullable<float> _Price;
		
		public ProductID_2022Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgName", DbType="NVarChar(200)")]
		public string ImgName
		{
			get
			{
				return this._ImgName;
			}
			set
			{
				if ((this._ImgName != value))
				{
					this._ImgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(200)")]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this._imgpath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catogries", DbType="NVarChar(200)")]
		public string Catogries
		{
			get
			{
				return this._Catogries;
			}
			set
			{
				if ((this._Catogries != value))
				{
					this._Catogries = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Real")]
		public System.Nullable<float> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
	
	public partial class Imag_20220907Result
	{
		
		private string _ImgName;
		
		private string _imgpath;
		
		private string _Catogries;
		
		private int _id;
		
		private System.Nullable<float> _Price;
		
		public Imag_20220907Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgName", DbType="NVarChar(200)")]
		public string ImgName
		{
			get
			{
				return this._ImgName;
			}
			set
			{
				if ((this._ImgName != value))
				{
					this._ImgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(200)")]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this._imgpath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catogries", DbType="NVarChar(200)")]
		public string Catogries
		{
			get
			{
				return this._Catogries;
			}
			set
			{
				if ((this._Catogries != value))
				{
					this._Catogries = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Real")]
		public System.Nullable<float> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
	
	public partial class Register20220909Result
	{
		
		private string _Name;
		
		private string _Password;
		
		private string _Gender;
		
		private string _Department;
		
		private string _Hobbies;
		
		private string _Emailaddress;
		
		public Register20220909Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(20)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(200)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hobbies", DbType="NVarChar(200)")]
		public string Hobbies
		{
			get
			{
				return this._Hobbies;
			}
			set
			{
				if ((this._Hobbies != value))
				{
					this._Hobbies = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emailaddress", DbType="NVarChar(255)")]
		public string Emailaddress
		{
			get
			{
				return this._Emailaddress;
			}
			set
			{
				if ((this._Emailaddress != value))
				{
					this._Emailaddress = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
